insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("노트북", "전자제품", 90000,"삼성", 100,"최신형 노트북")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("선풍기", "가전제품", 5000,"LG", 80,"탁상용")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("시리얼", "먹거리", 10000,"농심", 100,"맛있는")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("냉장고", "전자제품", 800000,"삼성", 50,"최신형 냉장고")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("전자레인지", "전자제품", 200000,"LG", 70,"잘돌아가는 전자레인지")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("햇반", "먹거리", 20000,"CJ", 200,"6개묶음")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("라면", "먹거리", 15000,"농심", 300,"신라면")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("휴대폰", "전자제품", 110000,"삼성", 100,"갤럭시 노트10 플러스")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("TV", "전자제품", 230000,"LG", 9000,"Full UHD")
insert into productTable(name, category, price, manufacturer,unitInStock, description) values ("아이스티", "먹거리", 2000,"립톤", 100,"복숭아맛")
